Main:
    HttpPort: 8082
    HttpsOn: false
    Domain: ""
    HttpsPort: 443
    PubDir: "static"
    ViewDir: "view/default"
    Youdb: "mydata.db"
    CookieSecure: false
    CookieHttpOnly: true
    OldSiteDomain: ""
    TLSCrtFile: ""
    TLSKeyFile: ""
Site:
    Name: "youBBS"
    Desc: "Yet another bbs in go"
    AdminEmail: ""
    MainDomain: "http://127.0.0.1:8082"
    MainNodeIds: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
    MustLoginNodeIds: "19"
    NotHomeNodeIds: "2,4,17,19"
    ProverbId: "2"
    AvatarMinId: 2539
    AvatarMaxId: 2558
    HomeNode: "2"
    AdminBotId: 2918
    AnonymousBotId: 2917
    TimeZone: 0
    HomeShowNum: 50
    PageShowNum: 20
    TagShowNum: 20
    CategoryShowNum: 20
    TitleMaxLen: 180
    ContentMaxLen: 9000
    PostInterval: 60
    CommentListNum: 10
    CommentInterval: 20
    Authorized: false
    RegReview: false
    CloseReg: false
    AutoDataBackup: false
    AutoGetTag: true
    UploadSuffix: ""
    UploadImgOnly: false
    UploadImgResize: false
    UploadMaxSize: 50
